sections:
  breadcrumbs:
    type: visual-debut::breadcrumbs

  product-details:
    type: visual-debut::product-details

  product-reviews:
    type: visual-debut::product-reviews

order:
  - breadcrumbs
  - product-details
  - product-reviews
